document.writeln("例如<a href=\"http://www.letv.com/\" target=\"_blank\">乐视</a>(映山红)：http://g3.letv.cn/1/41/103/2011012200.0.flv?start={start_bytes}<br>");
document.writeln("例如<a href=\"http://www.youku.com/\" target=\"_blank\">优酷</a>：http://v.youku.com/v_show/id_XMjQyMzQ1OTEy.html把XMjQyMzQ1OTEy填到下框，<b>类型:</b>必须选择优酷代理。<br>");
document.writeln("例如<a href=\"http://www.tudou.com/\" target=\"_blank\">土豆</a>：http://www.tudou.com/programs/view/MNXCD8a7yqg/查看网页源文件找到iid = 115136708，那么把{tid}115136708&rd={rd}填到下框，<b>类");
document.writeln("型:</b>必须选择土豆代理。<br>");
document.writeln("例如<a href=\"http://www.iqiyi.com/\" target=\"_blank\">奇异</a>：http://www.iqiyi.com/yinyue/20120122/af0531e95dd739cd.html查看网页源文件找到videoId : \"7bae01f1898b48eb8a28b17e4dada920\"、pid : ");
document.writeln("\"1318\"、ptype : \"2\"，那么把{qy}7bae01f1898b48eb8a28b17e4dada920/1318/2/填到下框，<b>类型:</b>必须选择奇异代理。<br>");
document.writeln("例如<a href=\"http://www.56.com/\" target=\"_blank\">56我乐</a>：http://f1.r.56.com/f1.c56.56.com/flvdownload/2/22/12854124643hd.flv?start={start_bytes}<br>");
document.writeln("例如<a href=\"http://www.youku.com/\" target=\"_blank\">优酷proxy插件演示</a>：http://v.youku.com/v_show/id_XMjQyMzQ1OTEy.html填【proxy:youku,XMjQyMzQ1OTEy】↓<br>");
document.writeln("例如<a href=\"http://video.sina.com.cn/\" target=\"_blank\">新浪proxy插件演示</a>：http://video.sina.com.cn/v/b/66980797-1717296611.html填【proxy:sina,66980797】↓<br>");
document.writeln("例如<a href=\"http://www.xiami.com/\" target=\"_blank\">虾米proxy插件演示</a>：http://www.xiami.com/song/1770624994/填【proxy:xiami,1770624994】↓<br>");
document.writeln("<a href=\"56sc\" target=\"_blank\"><b>你也可以去56视频第一代第二代播放器生成地址去生成。</b></a><br>");
document.writeln("【<a href=\"http://bbs.cenfun.com/thread-17263-1-1.html\" target=\"_blank\"><b>56直播调用CMP的生成方法</b></a>】 | 【<a href=\"http://xiu.56.com/api/userFlvApi.php?room_user_id=【输入room_user_id】");
document.writeln("\" target=\"_blank\"><b>56直播地址查询</b></a>】，token=后面的被容就是src地址<br>");
document.writeln("<b>注意：如果添加列表时此处请填&，如填写rtmp地址时此处为src参数。</b><br>");
document.writeln("");
